queue: clean up a covered switch
clang objects to the `default` case in a covered switch:

	src/queue.c:1127:2: error: default label in switch which covers all enumeration values [-Werror,-Wcovered-switch-default]

Remove the label, relying on the covered switch to catch the issue.