Fix unistd.h check.
This patch fixes this compiler error.

/usr/include/dispatch/dispatch.h:38:45: error: expected value in expression
                                            ^

Fixes: 8af68ef3e4bb ("fix invalid use of config defines in API/SPI headers")
Signed-off-by: Vinson Lee <vlee@freedesktop.org>