tests: fix -Werror,-Wimplicit-int-float-conversion
```
testes/dispatch_timer_short.c:58:74: error: implicit conversion from 'unsigned long long' to 'double' may loose precision [-Werror,-Wimplicit-int-float-conversion]
	test_long_less_than("Frequency", 1, (long)ceil((double)delay/(finalCount*interval)));
	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
```

Fix the casting for `finalCount` and explicitly cast the result which would be
an `unsigned long long` due to the multiplication by `interval`.